apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: azure                             
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: ccee541d-6755-4068-8fe0-e65de3acd2a1  # workload user managed identity ID
    keyvaultName: secretsvaultrjp        # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: mysecretvalue
          objectAlias: apikey
          objectType: secret
          objectVersion: ""            
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3