apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ccee541d-6755-4068-8fe0-e65de3acd2a1 # id of azure user managed identity
  name: cluster-workload-user
  namespace: default
